from card import *

def test_cards():
    pdf = Cards("L", "pt", (360,576))
    pdf.set_font("Arial", size=12)
    pdf.set_margins(40,30)

    card = Card("Title")
    card2 = Card("Title 2")

    pdf.add_card(card)
    pdf.add_card(card2)
    pdf.add_card(card)

    card.add_content(Subtitle("Sub1"))
    card.add_content(BulletedPoint("P1"))
    card.add_content(BulletedPoint("P2"))
    card.add_content(BulletedPoint("P3",1))
    card.add_content(BulletedPoint("P4",2))
    card.add_content(Subtitle("Sub2"))
    card.add_content(NumberedPoint("P1", number=1))
    card.add_content(NumberedPoint("P1", number=99))
    card.add_content(NumberedPoint("P1", number=1))
    card.add_content(NumberedPoint("P2", number=2, level=1))
    card.add_content(NumberedPoint("P3", number=3, level=1))
    card.add_content(NumberedPoint("P4", number=4, level=2))

    card2.add_content(Subtitle("Sub1"))
    card2.add_content(BulletedPoint("P1"))
    card2.add_content(BulletedPoint("P2"))
    card2.add_content(BulletedPoint("P3",1))
    card2.add_content(BulletedPoint("P4",2))
    card2.add_content(BulletedPoint("P1"))
    card2.add_content(BulletedPoint("P2"))
    card2.add_content(BulletedPoint("P3",1))
    card2.add_content(BulletedPoint("P4",2))
    card2.add_content(BulletedPoint("P1"))
    card2.add_content(BulletedPoint("P2"))
    card2.add_content(BulletedPoint("P3",1))
    card2.add_content(BulletedPoint("P4",2))
    card2.add_content(BulletedPoint("P1"))
    card2.add_content(BulletedPoint("P2"))
    card2.add_content(BulletedPoint("P3",1))
    card2.add_content(BulletedPoint("P4",2))
    card2.add_content(Subtitle("Sub2"))
    card2.add_content(NumberedPoint("P1", number=1))
    card2.add_content(NumberedPoint("P1", number=99))
    card2.add_content(NumberedPoint("P1", number=1))
    card2.add_content(NumberedPoint("P2", number=2, level=1))
    card2.add_content(NumberedPoint("P3", number=3, level=1))
    card2.add_content(NumberedPoint("P4", number=4, level=2))

    pdf.export("test.pdf")
